// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObraSmart.Infrastructure.Data;

#nullable disable

namespace ObraSmart.Infrastructure.Migrations
{
    [DbContext(typeof(ObraSmartDbContext))]
    [Migration("20260623135703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObraSmart.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.ComponenteAPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EstructuraAPUId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraAPUId");

                    b.HasIndex("InsumoId");

                    b.ToTable("ComponentesAPU");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Cotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchivoPdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId")
                        .IsUnique();

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.EstructuraAPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoTotalCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstructurasAPU");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioReferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoInsumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.ItemPresupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadItem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EstructuraAPUOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitarioCalculado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraAPUOrigenId");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("ItemsPresupuesto");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Presupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.RecursoItemPresupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotalRecurso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionCongelada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ItemPresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitarioCongelado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoInsumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemPresupuestoId");

                    b.ToTable("RecursosItemPresupuesto");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagoPredeterminada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValidezCotizacionDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.ComponenteAPU", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.EstructuraAPU", "EstructuraAPU")
                        .WithMany("Componentes")
                        .HasForeignKey("EstructuraAPUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObraSmart.Domain.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstructuraAPU");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Cotizacion", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.Presupuesto", "Presupuesto")
                        .WithOne("Cotizacion")
                        .HasForeignKey("ObraSmart.Domain.Entities.Cotizacion", "PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.EstructuraAPU", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.Usuario", "Usuario")
                        .WithMany("EstructurasAPU")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Insumo", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Insumos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.ItemPresupuesto", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.EstructuraAPU", "EstructuraAPUOrigen")
                        .WithMany()
                        .HasForeignKey("EstructuraAPUOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ObraSmart.Domain.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstructuraAPUOrigen");

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Presupuesto", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ObraSmart.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Presupuestos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.RecursoItemPresupuesto", b =>
                {
                    b.HasOne("ObraSmart.Domain.Entities.ItemPresupuesto", "ItemPresupuesto")
                        .WithMany("Recursos")
                        .HasForeignKey("ItemPresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPresupuesto");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.EstructuraAPU", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.ItemPresupuesto", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Presupuesto", b =>
                {
                    b.Navigation("Cotizacion");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ObraSmart.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("EstructurasAPU");

                    b.Navigation("Insumos");

                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
